use std::{
    fmt,
    str::FromStr
};

/// A Minecraft [biome](https://minecraft.gamepedia.com/Biome).
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Biome {
    Ocean,
    DeepOcean,
    FrozenOcean,
    DeepFrozenOcean,
    ColdOcean,
    DeepColdOcean,
    LukewarmOcean,
    DeepLukewarmOcean,
    WarmOcean,
    DeepWarmOcean,
    River,
    FrozenRiver,
    Beach,
    StoneShore,
    SnowyBeach,
    Forest,
    WoodedHills,
    FlowerForest,
    BirchForest,
    BirchForestHills,
    TallBirchForest,
    TallBirchHills,
    DarkForest,
    DarkForestHills,
    Jungle,
    JungleHills,
    ModifiedJungle,
    JungleEdge,
    ModifiedJungleEdge,
    BambooJungle,
    BambooJungleHills,
    Taiga,
    TaigaHills,
    TaigaMountains,
    SnowyTaiga,
    SnowyTaigaHills,
    SnowyTaigaMountains,
    GiantTreeTaiga,
    GiantTreeTaigaHills,
    GiantSpruceTaiga,
    GiantSpruceTaigaHills,
    MushroomFields,
    MushroomFieldShore,
    Swamp,
    SwampHills,
    Savanna,
    SavannaPlateau,
    ShatteredSavanna,
    ShatteredSavannaPlateau,
    Plains,
    SunflowerPlains,
    Desert,
    DesertHills,
    DesertLakes,
    SnowyTundra,
    SnowyMountains,
    IceSpikes,
    Mountains,
    WoodedMountains,
    GravellyMountains,
    GravellyMountainsPlus,
    MountainEdge,
    Badlands,
    BadlandsPlateau,
    ModifiedBadlandsPlateau,
    WoodedBadlandsPlateau,
    ModifiedWoodedBadlandsPlateau,
    ErodedBadlands,
    NetherWastes,
    CrimsonForest,
    WarpedForest,
    SoulSandValley,
    BasaltDeltas,
    TheEnd,
    SmallEndIslands,
    EndMidlands,
    EndHighlands,
    EndBarrens,
    TheVoid
}

impl Biome {
    /// Returns the biome with the given numeric ID.
    ///
    /// Returns `None` if the biome ID is unknown. This can happen if new biomes are added to Minecraft and this library is not yet updated.
    pub fn from_id(id: i32) -> Option<Biome> {
        match id {
            0 => Some(Biome::Ocean),
            24 => Some(Biome::DeepOcean),
            10 => Some(Biome::FrozenOcean),
            50 => Some(Biome::DeepFrozenOcean),
            46 => Some(Biome::ColdOcean),
            49 => Some(Biome::DeepColdOcean),
            45 => Some(Biome::LukewarmOcean),
            48 => Some(Biome::DeepLukewarmOcean),
            44 => Some(Biome::WarmOcean),
            47 => Some(Biome::DeepWarmOcean),
            7 => Some(Biome::River),
            11 => Some(Biome::FrozenRiver),
            16 => Some(Biome::Beach),
            25 => Some(Biome::StoneShore),
            26 => Some(Biome::SnowyBeach),
            4 => Some(Biome::Forest),
            18 => Some(Biome::WoodedHills),
            132 => Some(Biome::FlowerForest),
            27 => Some(Biome::BirchForest),
            28 => Some(Biome::BirchForestHills),
            155 => Some(Biome::TallBirchForest),
            156 => Some(Biome::TallBirchHills),
            29 => Some(Biome::DarkForest),
            157 => Some(Biome::DarkForestHills),
            21 => Some(Biome::Jungle),
            22 => Some(Biome::JungleHills),
            149 => Some(Biome::ModifiedJungle),
            23 => Some(Biome::JungleEdge),
            151 => Some(Biome::ModifiedJungleEdge),
            168 => Some(Biome::BambooJungle),
            169 => Some(Biome::BambooJungleHills),
            5 => Some(Biome::Taiga),
            19 => Some(Biome::TaigaHills),
            133 => Some(Biome::TaigaMountains),
            30 => Some(Biome::SnowyTaiga),
            31 => Some(Biome::SnowyTaigaHills),
            158 => Some(Biome::SnowyTaigaMountains),
            32 => Some(Biome::GiantTreeTaiga),
            33 => Some(Biome::GiantTreeTaigaHills),
            160 => Some(Biome::GiantSpruceTaiga),
            161 => Some(Biome::GiantSpruceTaigaHills),
            14 => Some(Biome::MushroomFields),
            15 => Some(Biome::MushroomFieldShore),
            6 => Some(Biome::Swamp),
            134 => Some(Biome::SwampHills),
            35 => Some(Biome::Savanna),
            36 => Some(Biome::SavannaPlateau),
            163 => Some(Biome::ShatteredSavanna),
            164 => Some(Biome::ShatteredSavannaPlateau),
            1 => Some(Biome::Plains),
            129 => Some(Biome::SunflowerPlains),
            2 => Some(Biome::Desert),
            17 => Some(Biome::DesertHills),
            130 => Some(Biome::DesertLakes),
            12 => Some(Biome::SnowyTundra),
            13 => Some(Biome::SnowyMountains),
            140 => Some(Biome::IceSpikes),
            3 => Some(Biome::Mountains),
            34 => Some(Biome::WoodedMountains),
            131 => Some(Biome::GravellyMountains),
            162 => Some(Biome::GravellyMountainsPlus),
            20 => Some(Biome::MountainEdge),
            37 => Some(Biome::Badlands),
            39 => Some(Biome::BadlandsPlateau),
            167 => Some(Biome::ModifiedBadlandsPlateau),
            38 => Some(Biome::WoodedBadlandsPlateau),
            166 => Some(Biome::ModifiedWoodedBadlandsPlateau),
            165 => Some(Biome::ErodedBadlands),
            8 => Some(Biome::NetherWastes),
            171 => Some(Biome::CrimsonForest),
            172 => Some(Biome::WarpedForest),
            170 => Some(Biome::SoulSandValley),
            173 => Some(Biome::BasaltDeltas),
            9 => Some(Biome::TheEnd),
            40 => Some(Biome::SmallEndIslands),
            41 => Some(Biome::EndMidlands),
            42 => Some(Biome::EndHighlands),
            43 => Some(Biome::EndBarrens),
            127 => Some(Biome::TheVoid),
            _ => None
        }
    }
}

impl FromStr for Biome {
    type Err = ();

    fn from_str(s: &str) -> Result<Biome, ()> {
        match s {
            "Ocean" => Ok(Biome::Ocean),
            "Deep Ocean" => Ok(Biome::DeepOcean),
            "Frozen Ocean" => Ok(Biome::FrozenOcean),
            "Deep Frozen Ocean" => Ok(Biome::DeepFrozenOcean),
            "Cold Ocean" => Ok(Biome::ColdOcean),
            "Deep Cold Ocean" => Ok(Biome::DeepColdOcean),
            "Lukewarm Ocean" => Ok(Biome::LukewarmOcean),
            "Deep Lukewarm Ocean" => Ok(Biome::DeepLukewarmOcean),
            "Warm Ocean" => Ok(Biome::WarmOcean),
            "Deep Warm Ocean" => Ok(Biome::DeepWarmOcean),
            "River" => Ok(Biome::River),
            "Frozen River" => Ok(Biome::FrozenRiver),
            "Beach" => Ok(Biome::Beach),
            "Stone Shore" => Ok(Biome::StoneShore),
            "Snowy Beach" => Ok(Biome::SnowyBeach),
            "Forest" => Ok(Biome::Forest),
            "Wooded Hills" => Ok(Biome::WoodedHills),
            "Flower Forest" => Ok(Biome::FlowerForest),
            "Birch Forest" => Ok(Biome::BirchForest),
            "Birch Forest Hills" => Ok(Biome::BirchForestHills),
            "Tall Birch Forest" => Ok(Biome::TallBirchForest),
            "Tall Birch Hills" => Ok(Biome::TallBirchHills),
            "Dark Forest" => Ok(Biome::DarkForest),
            "Dark Forest Hills" => Ok(Biome::DarkForestHills),
            "Jungle" => Ok(Biome::Jungle),
            "Jungle Hills" => Ok(Biome::JungleHills),
            "Modified Jungle" => Ok(Biome::ModifiedJungle),
            "Jungle Edge" => Ok(Biome::JungleEdge),
            "Modified Jungle Edge" => Ok(Biome::ModifiedJungleEdge),
            "Bamboo Jungle" => Ok(Biome::BambooJungle),
            "Bamboo Jungle Hills" => Ok(Biome::BambooJungleHills),
            "Taiga" => Ok(Biome::Taiga),
            "Taiga Hills" => Ok(Biome::TaigaHills),
            "Taiga Mountains" => Ok(Biome::TaigaMountains),
            "Snowy Taiga" => Ok(Biome::SnowyTaiga),
            "Snowy Taiga Hills" => Ok(Biome::SnowyTaigaHills),
            "Snowy Taiga Mountains" => Ok(Biome::SnowyTaigaMountains),
            "Giant Tree Taiga" => Ok(Biome::GiantTreeTaiga),
            "Giant Tree Taiga Hills" => Ok(Biome::GiantTreeTaigaHills),
            "Giant Spruce Taiga" => Ok(Biome::GiantSpruceTaiga),
            "Giant Spruce Taiga Hills" => Ok(Biome::GiantSpruceTaigaHills),
            "Mushroom Fields" => Ok(Biome::MushroomFields),
            "Mushroom Field Shore" => Ok(Biome::MushroomFieldShore),
            "Swamp" => Ok(Biome::Swamp),
            "Swamp Hills" => Ok(Biome::SwampHills),
            "Savanna" => Ok(Biome::Savanna),
            "Savanna Plateau" => Ok(Biome::SavannaPlateau),
            "Shattered Savanna" => Ok(Biome::ShatteredSavanna),
            "Shattered Savanna Plateau" => Ok(Biome::ShatteredSavannaPlateau),
            "Plains" => Ok(Biome::Plains),
            "Sunflower Plains" => Ok(Biome::SunflowerPlains),
            "Desert" => Ok(Biome::Desert),
            "Desert Hills" => Ok(Biome::DesertHills),
            "Desert Lakes" => Ok(Biome::DesertLakes),
            "Snowy Tundra" => Ok(Biome::SnowyTundra),
            "Snowy Mountains" => Ok(Biome::SnowyMountains),
            "Ice Spikes" => Ok(Biome::IceSpikes),
            "Mountains" => Ok(Biome::Mountains),
            "Wooded Mountains" => Ok(Biome::WoodedMountains),
            "Gravelly Mountains" => Ok(Biome::GravellyMountains),
            "Gravelly Mountains+" => Ok(Biome::GravellyMountainsPlus),
            "Mountain Edge" => Ok(Biome::MountainEdge),
            "Badlands" => Ok(Biome::Badlands),
            "Badlands Plateau" => Ok(Biome::BadlandsPlateau),
            "Modified Badlands Plateau" => Ok(Biome::ModifiedBadlandsPlateau),
            "Wooded Badlands Plateau" => Ok(Biome::WoodedBadlandsPlateau),
            "Modified Wooded Badlands Plateau" => Ok(Biome::ModifiedWoodedBadlandsPlateau),
            "Eroded Badlands" => Ok(Biome::ErodedBadlands),
            "Nether Wastes" => Ok(Biome::NetherWastes),
            "Crimson Forest" => Ok(Biome::CrimsonForest),
            "Warped Forest" => Ok(Biome::WarpedForest),
            "Soul Sand Valley" => Ok(Biome::SoulSandValley),
            "Basalt Deltas" => Ok(Biome::BasaltDeltas),
            "The End" => Ok(Biome::TheEnd),
            "Small End Islands" => Ok(Biome::SmallEndIslands),
            "End Midlands" => Ok(Biome::EndMidlands),
            "End Highlands" => Ok(Biome::EndHighlands),
            "End Barrens" => Ok(Biome::EndBarrens),
            "The Void" => Ok(Biome::TheVoid),
            _ => Err(())
        }
    }
}

impl fmt::Display for Biome {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Biome::Ocean => write!(f, "Ocean"),
            Biome::DeepOcean => write!(f, "Deep Ocean"),
            Biome::FrozenOcean => write!(f, "Frozen Ocean"),
            Biome::DeepFrozenOcean => write!(f, "Deep Frozen Ocean"),
            Biome::ColdOcean => write!(f, "Cold Ocean"),
            Biome::DeepColdOcean => write!(f, "Deep Cold Ocean"),
            Biome::LukewarmOcean => write!(f, "Lukewarm Ocean"),
            Biome::DeepLukewarmOcean => write!(f, "Deep Lukewarm Ocean"),
            Biome::WarmOcean => write!(f, "Warm Ocean"),
            Biome::DeepWarmOcean => write!(f, "Deep Warm Ocean"),
            Biome::River => write!(f, "River"),
            Biome::FrozenRiver => write!(f, "Frozen River"),
            Biome::Beach => write!(f, "Beach"),
            Biome::StoneShore => write!(f, "Stone Shore"),
            Biome::SnowyBeach => write!(f, "Snowy Beach"),
            Biome::Forest => write!(f, "Forest"),
            Biome::WoodedHills => write!(f, "Wooded Hills"),
            Biome::FlowerForest => write!(f, "Flower Forest"),
            Biome::BirchForest => write!(f, "Birch Forest"),
            Biome::BirchForestHills => write!(f, "Birch Forest Hills"),
            Biome::TallBirchForest => write!(f, "Tall Birch Forest"),
            Biome::TallBirchHills => write!(f, "Tall Birch Hills"),
            Biome::DarkForest => write!(f, "Dark Forest"),
            Biome::DarkForestHills => write!(f, "Dark Forest Hills"),
            Biome::Jungle => write!(f, "Jungle"),
            Biome::JungleHills => write!(f, "Jungle Hills"),
            Biome::ModifiedJungle => write!(f, "Modified Jungle"),
            Biome::JungleEdge => write!(f, "Jungle Edge"),
            Biome::ModifiedJungleEdge => write!(f, "Modified Jungle Edge"),
            Biome::BambooJungle => write!(f, "Bamboo Jungle"),
            Biome::BambooJungleHills => write!(f, "Bamboo Jungle Hills"),
            Biome::Taiga => write!(f, "Taiga"),
            Biome::TaigaHills => write!(f, "Taiga Hills"),
            Biome::TaigaMountains => write!(f, "Taiga Mountains"),
            Biome::SnowyTaiga => write!(f, "Snowy Taiga"),
            Biome::SnowyTaigaHills => write!(f, "Snowy Taiga Hills"),
            Biome::SnowyTaigaMountains => write!(f, "Snowy Taiga Mountains"),
            Biome::GiantTreeTaiga => write!(f, "Giant Tree Taiga"),
            Biome::GiantTreeTaigaHills => write!(f, "Giant Tree Taiga Hills"),
            Biome::GiantSpruceTaiga => write!(f, "Giant Spruce Taiga"),
            Biome::GiantSpruceTaigaHills => write!(f, "Giant Spruce Taiga Hills"),
            Biome::MushroomFields => write!(f, "Mushroom Fields"),
            Biome::MushroomFieldShore => write!(f, "Mushroom Field Shore"),
            Biome::Swamp => write!(f, "Swamp"),
            Biome::SwampHills => write!(f, "Swamp Hills"),
            Biome::Savanna => write!(f, "Savanna"),
            Biome::SavannaPlateau => write!(f, "Savanna Plateau"),
            Biome::ShatteredSavanna => write!(f, "Shattered Savanna"),
            Biome::ShatteredSavannaPlateau => write!(f, "Shattered Savanna Plateau"),
            Biome::Plains => write!(f, "Plains"),
            Biome::SunflowerPlains => write!(f, "Sunflower Plains"),
            Biome::Desert => write!(f, "Desert"),
            Biome::DesertHills => write!(f, "Desert Hills"),
            Biome::DesertLakes => write!(f, "Desert Lakes"),
            Biome::SnowyTundra => write!(f, "Snowy Tundra"),
            Biome::SnowyMountains => write!(f, "Snowy Mountains"),
            Biome::IceSpikes => write!(f, "Ice Spikes"),
            Biome::Mountains => write!(f, "Mountains"),
            Biome::WoodedMountains => write!(f, "Wooded Mountains"),
            Biome::GravellyMountains => write!(f, "Gravelly Mountains"),
            Biome::GravellyMountainsPlus => write!(f, "Gravelly Mountains+"),
            Biome::MountainEdge => write!(f, "Mountain Edge"),
            Biome::Badlands => write!(f, "Badlands"),
            Biome::BadlandsPlateau => write!(f, "Badlands Plateau"),
            Biome::ModifiedBadlandsPlateau => write!(f, "Modified Badlands Plateau"),
            Biome::WoodedBadlandsPlateau => write!(f, "Wooded Badlands Plateau"),
            Biome::ModifiedWoodedBadlandsPlateau => write!(f, "Modified Wooded Badlands Plateau"),
            Biome::ErodedBadlands => write!(f, "Eroded Badlands"),
            Biome::NetherWastes => write!(f, "Nether Wastes"),
            Biome::CrimsonForest => write!(f, "Crimson Forest"),
            Biome::WarpedForest => write!(f, "Warped Forest"),
            Biome::SoulSandValley => write!(f, "Soul Sand Valley"),
            Biome::BasaltDeltas => write!(f, "Basalt Deltas"),
            Biome::TheEnd => write!(f, "The End"),
            Biome::SmallEndIslands => write!(f, "Small End Islands"),
            Biome::EndMidlands => write!(f, "End Midlands"),
            Biome::EndHighlands => write!(f, "End Highlands"),
            Biome::EndBarrens => write!(f, "End Barrens"),
            Biome::TheVoid => write!(f, "The Void")
        }
    }
}
